# 参考https://jekyllrb.com/docs/configuration/front-matter-defaults/ 进行设置
title: SEU-HPC
description: 饮水思源，积健为雄
logo: https://qiniuyun.hrlee.cn/CSWu-banner.png
defaults: # 将所有配置选项使用<https://jekyllrb.com/docs/configuration/front-matter-defaults/>功能进行配置
  - scope:
      path: "" # an empty string here means all files in the project
    values: # 以下配置项也可以在任意页面自定义
      jekyll-theme-cswu: # 自定义主题的名字空间
        default:
          body:
            theme-base: theme-base-08 # 可选的主题色包括08~0f，见 <https://github.com/poole/lanyon>
            layout-reverse: false # 开启后sidebar在右边，反之左边
            sidebar-overlay: true # 开启后正文不随sidebar移动而移动
          append_to_head: # 通过内嵌html的方式引入并定制插件，删改前确定知道自己在做什么。定制插件的方式可以参考这篇文章 <https://wu-kan.cn/_posts/2019-01-18-基于Jekyll搭建个人博客/>
            - | #一些页面优化标签，看不懂可跳过
              <meta
                name="viewport"
                content="width=device-width,minimum-scale=1,initial-scale=1"
              />
              <meta
                http-equiv="content-type"
                content="text/html; charset=utf-8"
              />
              <link
                rel="alternate"
                href="/feed.xml"
                title="RSS"
                type="application/rss+xml"
              />
            - | # 网站小图标
              <link
                rel="apple-touch-icon-precomposed"
                href="https://qiniuyun.hrlee.cn/CSWu-banner.png"
              />
              <link
                rel="shortcut
                icon"
                href="https://i.loli.net/2021/04/10/HI95xRVNA6zwseO.png"
              />
            - | # 来自lanyon的页面样式，不要改
              <link
                rel="stylesheet"
                href="https://cdn.jsdelivr.net/combine/gh/poole/lanyon@v1.1.0/public/css/poole.min.css,gh/poole/lanyon@v1.1.0/public/css/lanyon.min.css,gh/poole/lanyon@v1.1.0/public/css/syntax.min.css"
              />
            - | # 用js引入fontawesome图标样式，功能更丰富
              <script
                async="async"
                src="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/js/all.min.js"
              ></script>
            - | # 网站字体，要换字体建议架梯子上<https://fonts.google.com/>挑选，再通过fonts.loli.net 加速引入
              <style>
                .sidebar,
                html,
                h1,
                h2,
                h3,
                h4,
                h5,
                h6 {
                  font-family: "Courier New", "Courier", "Hiragino Sans GB", "WenQuanYi Micro Hei", "Microsoft YaHei Light", "Microsoft JhengHei", monospace;
                }
              </style>
            - | # 表格样式美化
              <style>
                td,
                th {
                  padding: 0px;
                  border: 0px;
                }
                table {
                  border: 0px;
                }
                table tbody {
                  display: block;
                  overflow: scroll;
                }
                table thead,
                tbody tr {
                  display: table;
                  table-layout: fixed;
                  width: 100%;
                }
              </style>
            - | #修复行内图片默认样式
              <style>
                img {
                  display: inline-block;
                  margin: 0;
                }
              </style>
            - | #修复行内图片默认样式
              <style>
                img {
                  display: inline-block;
                  margin: 0;
                }
              </style>
          sidebar: # 此配置项下是一些关于侧边栏的配置
            disable: false # 是否不显示sidebar
            nav: # 导航部分的内容，你也可以自己增加文字、图标（来自fontawesome）和对应的链接
              - title: '<i class="fas fa-home fa-fw"></i> Index'
                href: /
              - title: '<i class="fas fa-award fa-fw"></i> Honors'
                href: /Honors/
              - title: '<i class="fas fa-users fa-fw"></i> Members'
                href: /Members/
              - title: '<i class="fas fa-file-powerpoint fa-fw"></i> Talks'
                href: /Talks/
              - title: '<i class="fas fa-address-book fa-fw"></i> Contact'
                href: /Contact/
              - title: '<i class="fab fa-github fa-fw"></i> GitHub'
                href: https://github.com/SYSU-SCC
            simple_jekyll_search: # 侧边栏的全站搜索
              enable: true
              full_text_search: false # 可能导致缓慢的搜索和加载
              append: | # 如果看不懂就不改
                <style>
                  #sidebar-search-input {
                    background: none;
                    border: none;
                    color: White;
                    width: 100%;
                  }
                  #sidebar-search-results-container {
                    overflow: auto auto;
                    max-height: 66.6vh;
                  }
                </style>
                <input
                  id="sidebar-search-input"
                  placeholder="Search"
                />
                <ol
                  id="sidebar-search-results-container"
                ></ol>
                <script
                  src='https://cdn.jsdelivr.net/npm/simple-jekyll-search@1.9.1'
                  async='async'
                  onload='
                    SimpleJekyllSearch({
                      json: "/assets/simple-jekyll-search/search.json",
                      searchInput: document.getElementById("sidebar-search-input"),
                      resultsContainer: document.getElementById("sidebar-search-results-container"),
                      searchResultTemplate: `<li><a href="{url}">{title}</a></li>`,
                      limit: 999,
                      fuzzy: true
                    })'
                ></script>
            jekyll-toc: # 侧边栏的目录插件，https://github.com/allejo/jekyll-toc
              enable: true
              prepend: | # 目录过长时自动折叠
                <style>
                  #toc {
                    overflow: auto auto;
                    max-height: 66.6vh;
                  }
                </style>
            append_to_sidebar:
              #- <script defer="defer" src="https://cdn.jsdelivr.net/gh/poole/lanyon@v1.1.0/public/js/script.min.js"></script> # 点击空白处而非按钮从而关闭侧边栏的插件，可选
              - | #修复点击侧边栏按钮回到顶部的问题
                <style>
                  .sidebar-checkbox {
                    display: none;
                  }
                  .sidebar-toggle {
                    position: fixed;
                  }
                </style>
              - | # 侧边栏头像效果
                <style>
                  .effect {
                    margin: 1rem;
                    perspective: 900px;
                  }
                  .effect-info {
                    text-align: center;
                    position: absolute;
                    top: 0;
                    transform-style: preserve-3d;
                  }
                  .effect-img {
                    z-index: 11;
                    width: 100%;
                    height: 100%;
                    position: relative;
                    transition: all 0.5s ease-in-out;
                  }
                  .effect-img:before {
                    position: absolute;
                    display: block;
                  }
                  .effect-right_to_left .effect-img {
                    transform-origin: 0% 50%;
                  }
                  .effect-right_to_left:hover .effect-img {
                    transform: rotate3d(0, 1, 0, -180deg);
                  }
                </style>
              - | # 运行时间，可将倒数第三行的时间改成你自己的建站时间，格式仿照上面的；不需要的话可以把这一项都删掉
                <div>
                  <i class="fas fa-cog fa-spin fa-fw"></i>
                  <span id="run_time_day">
                    <i class="fas fa-spinner fa-pulse"></i>
                  </span>d
                  <span id="run_time_hour">
                    <i class="fas fa-spinner fa-pulse"></i>
                  </span>h
                  <span id="run_time_minute">
                    <i class="fas fa-spinner fa-pulse"></i>
                  </span>m
                  <span id="run_time_second">
                    <i class="fas fa-spinner fa-pulse"></i>
                  </span>s
                  <script>
                    setInterval(function (d,h,m,s,b) {
                      function setzero(i) {
                        return i < 10 ? "0" + i : i;
                      }
                      let BirthDay = new Date(b);
                      let today = new Date();
                      let timeold = (today.getTime() - BirthDay.getTime());
                      let sectimeold = timeold / 1000;
                      let secondsold = Math.floor(sectimeold);
                      let msPerDay = 24 * 60 * 60 * 1000;
                      let e_daysold = timeold / msPerDay;
                      let daysold = Math.floor(e_daysold);
                      let e_hrsold = (e_daysold - daysold) * 24;
                      let hrsold = Math.floor(e_hrsold);
                      let e_minsold = (e_hrsold - hrsold) * 60;
                      let minsold = Math.floor((e_hrsold - hrsold) * 60);
                      let seconds = Math.floor((e_minsold - minsold) * 60);
                      d.textContent = daysold;
                      h.textContent = setzero(hrsold);
                      m.textContent = setzero(minsold);
                      s.textContent = setzero(seconds);
                    },
                    1000,
                    document.getElementById("run_time_day"),
                    document.getElementById("run_time_hour"),
                    document.getElementById("run_time_minute"),
                    document.getElementById("run_time_second"),
                    "10/04/2012 11:03:56")// 建队时间？
                  </script>
                </div>
              - | # 不蒜子页面统计，看不懂可不改
                <div>
                  <div>
                    <i class="fas fa-eye fa-fw"></i>
                    <span id="busuanzi_value_page_pv">
                      <i class="fas fa-spinner fa-pulse"></i>
                    </span>
                  </div>
                  <div>
                    <i class="fas fa-paw fa-fw"></i>
                    <span id="busuanzi_value_site_pv">
                      <i class="fas fa-spinner fa-pulse"></i>
                    </span>
                  </div>
                  <div>
                    <i class="fas fa-user-friends fa-fw"></i>
                    <span id="busuanzi_value_site_uv">
                      <i class="fas fa-spinner fa-pulse"></i>
                    </span>
                  </div>
                  <script
                    src='https://cdn.jsdelivr.net/npm/busuanzi@2.3.0'
                    async='async'
                  ></script>
                </div>
            wordcount: # 全站字数统计
              enable: true # 本地调试时建议关闭，非常影响站点生成速度（所需时间与博文数量的平方成正比）
              prepend: <i class="fas fa-user-edit fa-fw"></i>
              kilo: k
              unit: words
        page:
          title: # 为每个页面自动生成一个 H1 title
            enable: true
          katex: # katex 数学公式插件
            enable: true
            append:
              | # 对KaTeX过长公式渲染超出页面的修正，感谢[@AmachiInori](https://github.com/wu-kan/wu-kan.github.io/issues/13)
              <link
                rel="stylesheet"
                href="https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/katex.min.css"
              />
              <style>
                .katex-display>.katex {
                  white-space: normal;
                }
              </style>
              <script
                src="https://cdn.jsdelivr.net/combine/npm/katex@0.13.11/dist/katex.min.js,npm/katex@0.13.11/dist/contrib/auto-render.min.js"
                async="async"
                onload='renderMathInElement(document.body, { delimiters: [{left: "
",right:"
", display: true}, { left: "",right:"", display: false }, {left: "\\(", right: "\\)", display: false}, {left: "\\[", right: "\\]", display: true}]})'
              ></script>
          mermaid: # mermaid图插件
            enable: true
            append: |
              <style>
                pre.language-mermaid,
                code.language-mermaid {
                  display: none;
                }
                @media only screen {
                  .mermaid {
                    overflow: auto auto;
                    max-width: 100%;
                    max-height: 66.6vh;
                  }
                }
              </style>
              <script
                src="https://cdn.jsdelivr.net/npm/mermaid@8.10.1/dist/mermaid.min.js"
                async="async"
                onload='
                  for(let x of document.getElementsByClassName("language-mermaid"))
                    if(x.nodeName=="CODE")
                    {
                      let m = document.createElement("div");
                      m.classList.add("mermaid");
                      m.textContent = x.textContent;
                      x.parentNode.insertAdjacentElement("beforebegin", m);
                    }'
              ></script>
          prism: # 代码高亮插件
            enable: true
            append: |
              <link
                rel="stylesheet"
                href="https://cdn.jsdelivr.net/combine/npm/prismjs@1.23.0/plugins/line-numbers/prism-line-numbers.min.css,npm/prismjs@1.23.0/plugins/toolbar/prism-toolbar.min.css,npm/prismjs@1.23.0/plugins/match-braces/prism-match-braces.min.css,npm/prism-themes@1.5.0/themes/prism-nord.min.css"
              />
              <script
                src="https://cdn.jsdelivr.net/combine/npm/prismjs@1.23.0/components/prism-core.min.js,npm/prismjs@1.23.0/plugins/autoloader/prism-autoloader.min.js,npm/prismjs@1.23.0/plugins/line-numbers/prism-line-numbers.min.js,npm/prismjs@1.23.0/plugins/toolbar/prism-toolbar.min.js,npm/prismjs@1.23.0/plugins/match-braces/prism-match-braces.min.js"
                async="async"
                data-autoloader-path="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/components/"
                onload='
                  for(let x of document.getElementsByClassName("content"))
                    x.classList.add("line-numbers","match-braces");
                  Prism.plugins.toolbar.registerButton("select-code", function (env) {
                    let button = document.createElement("button");
                    button.textContent = "select this " + env.language;
                    button.addEventListener("click", function () {
                      if (document.body.createTextRange) {
                        let range = document.body.createTextRange();
                        range.moveToElementText(env.element);
                        range.select();
                      } else if (window.getSelection) {
                        let selection = window.getSelection();
                        let range = document.createRange();
                        range.selectNodeContents(env.element);
                        selection.removeAllRanges();
                          selection.addRange(range);
                      }
                    });
                    return button;
                  })'
              ></script>
          prepend:
            - | # 代码块过长自动折叠
              <style>
                @media only screen {
                  pre {
                    max-height: 66.6vh;
                    overflow: auto;
                  }
                }
              </style>
            - | # 增加宽屏下的显示内容
              <style>
                .container {
                  min-width: 66.6%;
                }
              </style>
            - | # 给文章加上磨砂背景，防止被背景影响阅读；同时加上加载动画
              <style>
                .container.content {
                  padding: 2rem;
                  animation-duration: 2s;
                  animation-name: fadeIn;
                }
                @keyframes fadeIn {
                  from {
                    opacity: 0;
                  }
                  to {
                    opacity: 1;
                  }
                }
              </style>
        comments:
          append: |
            <script src="https://utteranc.es/client.js"
              repo="SYSU-SCC/SYSU-SCC.github.io"
              issue-term="url"
              theme="github-light"
              crossorigin="anonymous"
              async
            ></script>
        home: # 展示页的配置可跳过，详见<https://revealjs.com/>
          append_to_section_tag:
            - key: data-markdown
            - key: data-separator # 水平展示页分隔符
              value: <!-- .slide -->
            - key: data-separator-vertical # 垂直展示页分隔符
              value: <!-- .slide vertical=true -->
            - key: data-background-color
              value: "White"
          prepend: |
            <link
              rel="stylesheet"
              href="https://cdn.jsdelivr.net/combine/npm/reveal.js@4.1.1/dist/reveal.min.css,npm/reveal.js@4.1.1/dist/theme/serif.min.css"
            />
            <style>
              .sidebar {
                line-height: 1.5;
              }
              .reveal .slides {
                text-align: left;
              }
              .reveal a {
                color: #268BD2;
              }
            </style>
          append: |
            <script
              async="async"
              src="https://cdn.jsdelivr.net/combine/npm/reveal.js@4.1.1/dist/reveal.min.js,npm/reveal.js@4.1.1/plugin/markdown/markdown.min.js,npm/reveal.js@4.1.1/plugin/math/math.min.js,npm/reveal.js@4.1.1/plugin/highlight/highlight.min.js"
              onload="
              for(let x of document.getElementsByClassName('wrap'))
                x.classList.add('reveal');
              Reveal.initialize({
                height: '100%',
                hash: true,
                mouseWheel: true,
                navigationMode: 'linear',
                plugins: [ RevealMarkdown,RevealMath,RevealHighlight ]
              });
            "></script>
compress_html: # <https://github.com/penibelst/jekyll-compress-html>
  clippings: all
  comments: [] # 注释不能压缩，否则 reveal.js 的 ppt切屏受影响
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

# githubpage上支持的插件见<https://pages.github.com/versions/>
plugins: # <https://jekyllrb.com/docs/plugins/>
  - jekyll-readme-index # 使用readme做index，从而和github渲染效果一致
  - jekyll-default-layout # 为每个markdown自动生成layout
  - jekyll-seo-tag # 为每个页面生成标题
  - jekyll-sitemap # 为站点生成站点地图
  - jekyll-feed # 为站点生成RSS源
  - jekyll-remote-theme # 使用remote_theme插件实现主题的前后分离，详见<https://github.com/benbalter/jekyll-remote-theme/>

remote_theme: https://github.com/wu-kan/jekyll-theme-WuK@4.1.0 #使用固定版本号以防止主题更新导致站点显示错乱

readme_index: # 缺失index.md和index.html时，使用README.md代替之
  with_frontmatter: true # 支持带有yaml头的README

permalink: pretty
# timezone: Asia/Shanghai # 解决githubpage显示时间不正确的问题，见<https://www.iana.org/time-zones>
future: true # 允许发布时间在未来的文章

# limit_posts: 999 # 限制博文数量
# encoding: utf-8

markdown: kramdown
kramdown: # 见<https://kramdown.gettalong.org/options.html>
  input: GFM # 见<http://jekyllcn.com/docs/configuration/#kramdown>
  syntax_highlighter_opts: # 可见<https://kramdown.gettalong.org/syntax_highlighter/rouge.html>
    block:
      disable: true # 关掉代码块默认的高亮，换用prismjs
      line_numbers: false #渲染出来的效果好鬼畜
    span:
      disable: true
